# Generated by Django 2.0.2 on 2018-05-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVapp', '0004_auto_20180529_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
