# Generated by Django 2.0.2 on 2018-05-29 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('lobe', models.CharField(max_length=200)),
                ('shape', models.CharField(max_length=200)),
                ('allothercomments', models.CharField(max_length=200)),
                ('img', models.ForeignKey(db_column='img', on_delete=django.db.models.deletion.DO_NOTHING, to='NVapp.Images')),
                ('scorer', models.ForeignKey(db_column='scorer', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Scores',
            },
        ),
    ]
