# Generated by Django 2.0.2 on 2018-05-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='allothercomments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='degree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='lobe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='quality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='shape',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
